const householdItems = [
    { name: "Rock", ability: "Deals 2 damage to the opponent." },
    { name: "Paper", ability: "Protects from the next 2 damage dealt to you." },
    { name: "Scissors", ability: "Deals 1 damage and discards one card from the opponent's hand." },
    { name: "Sponge", ability: "Heals you for 1 life point." },
    { name: "Knife", ability: "Deals 3 damage but can only be played if you have less than 5 life points." },
    { name: "Cup", ability: "Blocks the next attack, giving you an extra turn." },
    { name: "Pan", ability: "Deals 2 damage and forces your opponent to skip their next turn." },
    { name: "Broom", ability: "Removes one of your opponent’s cards from their hand for this turn." },
    { name: "Mop", ability: "Cleans up (removes all effects from previous attacks for one round)." },
    { name: "Tape", ability: "Prevents your opponent from using any card abilities next turn." },
    { name: "Fork", ability: "Deals 1 damage and allows you to draw an extra card." },
    { name: "Spoon", ability: "Heals 2 life points but can't be played if your life points are full." },
    { name: "Plate", ability: "Protects against the next 3 damage received." },
    { name: "Trash Can", ability: "Discards one of your opponent's cards at random from their hand." },
    { name: "Light Bulb", ability: "Look at your opponent's hand and choose one card to discard." },
    { name: "Window", ability: "Prevents the next attack by reflecting it back (deals 1 damage to the attacker)." },
    { name: "Toaster", ability: "Deals 2 damage but requires you to skip your next turn." },
    { name: "Frying Pan", ability: "Deals 3 damage and prevents the opponent from healing for one turn." },
    { name: "Bathroom Scale", ability: "Each player draws 1 card, but you cannot attack this turn." },
    { name: "Glove", ability: "Allows you to block one attack entirely and draw a card." },
    { name: "Vacuum", ability: "Removes all negative effects from you but cannot be played if you have no damage." },
    { name: "Ladder", ability: "Skip one of your opponent’s attack turns." },
    { name: "Mirror", ability: "Reflects 1 damage back to your opponent." },
    { name: "Candle", ability: "Deals 1 damage and makes your opponent discard a card." },
    { name: "Baking Sheet", ability: "Deals 2 damage but prevents you from healing for one turn." },
    { name: "Dish Soap", ability: "Doubles the effect of the next card you play." },
    { name: "Couch", ability: "Provides 3 temporary health points but cannot be used for an attack." },
    { name: "Broomstick", ability: "Discards one opponent's card." },
    { name: "Clock", ability: "Skips an opponent’s next turn." },
    { name: "Fridge", ability: "Heals 1 life point for every card you have in hand (up to a maximum of 3)." },
    { name: "Sewing Kit", ability: "Heals 2 life points but can only be used once per game." },
    { name: "Ice Tray", ability: "Freezes the opponent's card for one turn (they skip their next turn)." },
    { name: "Juicer", ability: "Deals 1 damage and restores 1 life point to you." },
    { name: "Camera", ability: "Look at the top 3 cards of your deck, rearrange them in any order." },
    { name: "Remote Control", ability: "Skip your next turn to gain an extra card draw." },
    { name: "Scented Candle", ability: "Heals 1 life point and allows you to shield against 1 attack next turn." },
    { name: "Dishwasher", ability: "Heals 1 life point and allows you to choose a card from your discard pile to return to your hand." },
    { name: "Plunger", ability: "Discards all negative effects from you." },
    { name: "Wh
